version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=images
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=secret